### ISSUE TITLE
This seems to require a run export

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/svt-av1-feedstock#12]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

@claydugo and I are running into an issue were we get an error with the latest sv1-env:
```
    svt-av1:                   1.1.0-h27087fc_0              conda-forge                                          
```
being incompatible with opencv

```
ImportError: libSvtAv1Enc.so.0: cannot open shared object file: No such file or directory
```

Clay will followup with a reproducible environment.

We likely need to add a runexport to this feedstock so that it gets caught by the migrator.

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by hmaarrfk** [comment]
I think a secondary issue is that opencv is linking to the library, even though it isn't explicitely listed in the dependencies. That seems like an opencv issue.

However, I think the issue still stands with the library:
https://github.com/conda-forge/opencv-feedstock/pull/316

**Comment by matthiasdiener** [comment]
Thank you for the report! #13 adds run_exports.

**Comment by hmaarrfk** [comment]
can we hold off on #13 until we patch the previous packages?

**Comment by hmaarrfk** [comment]
and can we likely mark the existing build as broken?

**Comment by matthiasdiener** [comment]
> can we hold off on #13 until we patch the previous packages?

> and can we likely mark the existing build as broken?

Sure. Please let me know what I need to do

**Comment by hmaarrfk** [comment]
Here is my proposal

1. I would like to mark the package 1.1 as broken to stop others from depending on it while we handle issues. https://conda-forge.org/docs/orga/guidelines.html?highlight=broken#fixing-broken-packages @matthiasdiener are you able to handle this
2. We need to find all packages that depended on version `0.9` and add a runtime dependency on `0.9` using the repodata patch: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock
3. Merge the 1.1 package you suggested.
4. Merge the migrator to ensure that FFMPEG (and others) gets rebuilt https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2888


part of this proposal hinges on my limited availablility during east coast daylight hours to address 2-4. I can likely merge the PR for `1.` quickly helping most users!

**Comment by carterbox** [comment]
I have opened a broken package request, but making a repodata patch was too complicated / not documented enough for me to do.

Suggestion: We migrate all 0.x builds to a new build of 0.9 that has an appropriate run_export, then we can re-release 1.x with the appropriate run_export because the 0.x to 1.x transition is API breaking, so there is no guarantee that a migration from 0.x to 1.x will work for all packages.

**Comment by jessemapel** [comment]
I've encountered this issue too on macOS 11.6.5. It seems I have a 1.1.0 version of the encode library but a 0.8.7 version of the decode library:

```
IGSWZAWGLT00014:ISIS3 jmapel$ ls $CONDA_PREFIX/lib/libSvt*
$CONDA_PREFIX/lib/libSvtAv1Dec.0.8.7.dylib	$CONDA_PREFIX/lib/libSvtAv1Enc.1.1.0.dylib
$CONDA_PREFIX/lib/libSvtAv1Dec.0.dylib	$CONDA_PREFIX/lib/libSvtAv1Enc.1.dylib
$CONDA_PREFIX/lib/libSvtAv1Dec.dylib		$CONDA_PREFIX/lib/libSvtAv1Enc.dylib
```


> I think a secondary issue is that opencv is linking to the library, even though it isn't explicitely listed in the dependencies. That seems like an opencv issue.

This looks to be expected. SVT AV1 is a dependency of ffmpeg which is a dependency of openCV

**Comment by jessemapel** [comment]
Okay, yeah. I looked at it more and adding a run_export appears correct. I'm getting an ffmpeg build that just has an un-pinned svt-av1 dependency:

```
IGSWZAWGLT00014:ISIS3 jmapel$ conda search --info -c conda-forge ffmpeg=4.4.1=h2579ba5_2
Loading channels: done
ffmpeg 4.4.1 h2579ba5_2
-----------------------
file name   : ffmpeg-4.4.1-h2579ba5_2.tar.bz2
name        : ffmpeg
version     : 4.4.1
build       : h2579ba5_2
build number: 2
size        : 10.5 MB
license     : GPL-3.0-or-later
subdir      : osx-64
url         : https://conda.anaconda.org/conda-forge/osx-64/ffmpeg-4.4.1-h2579ba5_2.tar.bz2
md5         : ddf5bdf1ed670612158ebb88432ee4f2
timestamp   : 2022-02-25 00:06:03 UTC
dependencies: 
  - aom >=3.3.0,<3.4.0a0
  - bzip2 >=1.0.8,<2.0a0
  - freetype >=2.10.4,<3.0a0
  - gmp >=6.2.1,<7.0a0
  - gnutls >=3.6.13,<3.7.0a0
  - lame >=3.100,<3.101.0a0
  - libcxx >=12.0.1
  - libiconv >=1.16,<1.17.0a0
  - libvpx >=1.11.0,<1.12.0a0
  - libxml2 >=2.9.12,<2.10.0a0
  - libzlib >=1.2.11,<1.3.0a0
  - openh264 >=2.1.1,<2.2.0a0
  - svt-av1
  - x264 >=1!161.3030,<1!162
  - x265
```

but then libavcodec from ffmpeg links major version 0

```
IGSWZAWGLT00014:ISIS3 jmapel$ otool -L $CONDA_PREFIX/lib/libavcodec.58.134.100.dylib
/Users/jmapel/miniconda3/envs/isis7_test/lib/libavcodec.58.134.100.dylib:
	@rpath/libavcodec.58.dylib (compatibility version 58.0.0, current version 58.134.100)
	@rpath/libswresample.3.dylib (compatibility version 3.0.0, current version 3.9.100)
	@rpath/libavutil.56.dylib (compatibility version 56.0.0, current version 56.70.100)
	@rpath/libvpx.7.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	@rpath/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
	@rpath/liblzma.5.dylib (compatibility version 8.0.0, current version 8.5.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 492.0.0)
	@rpath/libaom.3.dylib (compatibility version 3.0.0, current version 3.3.0)
	@rpath/libmp3lame.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libSvtAv1Enc.0.dylib (compatibility version 0.0.0, current version 0.9.1)
	@rpath/libx264.161.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libx265.199.dylib (compatibility version 199.0.0, current version 199.0.0)
	@rpath/libopenh264.6.dylib (compatibility version 2.1.0, current version 2.1.1)
	/System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 853.0.0)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.8.0)
```

Sorry if this is just a whole bunch of redundant information! I really appreciate you getting on top of this so fast.

**Comment by Tobias-Fischer** [comment]
Let's leave it open till https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/263 is merged?

**Comment by jakirkham** [comment]
Maybe it's time to merge PR ( https://github.com/conda-forge/conda-forge.github.io/pull/1688 )

**Comment by hmaarrfk** [comment]
seems like a new ffmpeg was built!!

Hopefully this isn't an issue anymore!

**Comment by h-vetinari** [comment]
> seems like a new ffmpeg was built!!
> 
> Hopefully this isn't an issue anymore!

Do we still need the rebuild for 4.4? It [looks](https://github.com/conda-forge/ffmpeg-feedstock/pull/134) ready, but I haven't been following this issue, so just wanted to ask first.
